from sqlalchemy import Column, Integer, String, DateTime, Text, ForeignKey
from datetime import datetime, timezone
from .database import Base

class User(Base):
    __tablename__ = "users"

    id              = Column(Integer, primary_key=True, index=True, autoincrement=True)
    username        = Column(String(100), unique=True, index=True, nullable=False)
    email           = Column(String(255), unique=True, index=True, nullable=False)
    hashed_password = Column(String(255), nullable=False)
    role            = Column(String(20), default="citizen")   # "citizen" | "lawyer"
    created_at      = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

class CaseMetadata(Base):
    """Stores metadata about downloaded SC judgments"""
    __tablename__ = "case_metadata"

    id         = Column(Integer, primary_key=True, index=True, autoincrement=True)
    case_name  = Column(Text, nullable=True)
    year       = Column(Integer, nullable=True)
    case_type  = Column(String(100), nullable=True)
    pdf_path   = Column(Text, nullable=True)
    link       = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

class Conversation(Base):
    """Stores citizen chatbot conversations"""
    __tablename__ = "conversations"

    id        = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id   = Column(Integer, ForeignKey("users.id"), nullable=False)
    question  = Column(Text, nullable=False)
    answer    = Column(Text, nullable=False)
    timestamp = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

class Draft(Base):
    """Stores AI-generated legal documents"""
    __tablename__ = "drafts"

    id         = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id    = Column(Integer, ForeignKey("users.id"), nullable=False)
    doc_type   = Column(String(100), nullable=False)
    title      = Column(String(255), nullable=False)
    content    = Column(Text, nullable=False)
    form_data  = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

class SimilaritySearch(Base):
    """Stores lawyer similarity search queries and results"""
    __tablename__ = "similarity_searches"

    id           = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id      = Column(Integer, ForeignKey("users.id"), nullable=False)
    query        = Column(Text, nullable=False)
    results_json = Column(Text, nullable=True)
    timestamp    = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

class LawyerDocument(Base):
    """Stores documents generated by lawyers (Bail, Legal Notice, etc.)"""
    __tablename__ = "lawyer_documents"

    id            = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id       = Column(Integer, ForeignKey("users.id"), nullable=False)
    document_type = Column(String(100), nullable=False) # "bail", "legal_notice", "written_arguments"
    case_title    = Column(String(255), nullable=False)
    content       = Column(Text, nullable=False)
    form_data     = Column(Text, nullable=True) # JSON store for form inputs
    created_at    = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

class Hearing(Base):
    """Stores case hearing schedules and tasks for lawyers"""
    __tablename__ = "hearings"

    id           = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id      = Column(Integer, ForeignKey("users.id"), nullable=False)
    case_title   = Column(String(255), nullable=False)
    hearing_date = Column(String(100), nullable=False) # Store as string for easy UI rendering (e.g. YYYY-MM-DD)
    bench        = Column(String(255), nullable=True)
    stage        = Column(String(100), nullable=True) # "Arguments", "Evidence", etc.
    notes        = Column(Text, nullable=True)
    created_at   = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
